### ISSUE TITLE
Update LSG module for Mendix World

### ISSUE THREAD

**Issue by RussellHite** [cdcharlebois/LivingStyleGuideModule#1]
Hey Conner, I'll be demoing the Living Style Guide Module at Mendix World. 
I did a run through of it yesterday and saw that the read only style on the dataview of the "Item_ReadOnly" page was set to Control instead of text which was causing some odd alignment issues for the tip and warning glyphicons.

I went ahead and updated the project and exported out the lsg module.
[LivingStyleGuide.mpk.zip](https://github.com/cdcharlebois/LivingStyleGuideModule/files/3060662/LivingStyleGuide.mpk.zip)

 Could you make sure I exported it correctly and update it in the app store?

**Comment by cdcharlebois** [comment]
what's in the _.zip_ file? did you just zip the _.mpk_ file?

**Comment by RussellHite** [comment]
Yeah

**Comment by cdcharlebois** [comment]
published! https://appstore.home.mendix.com/link/app/105886/Mendix/Living-Style-Guide
